//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// SimulatorPrototype.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIMULATOR_PROTOTYPE_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_SEL_OPTION                  131
#define IDI_ICON1                       133
#define IDI_ICON2                       134
#define IDI_ICON3                       135
#define IDI_ICON4                       136
#define IDB_DEVICES                     138
#define IDB_DEVICES1                    139
#define IDD_DIALOG1                     144
#define IDD_SEL_OPTION2                 144
#define IDD_SEL_CREATEMODULE            146
#define IDD_DIALOG2                     150
#define IDD_SEL_UPDATEMODULE            152
#define IDD_DIALOG_LPM                  154
#define IDD_DIALOG_ATM                  155
#define IDD_DIALOG_LL                   156
#define IDD_DIALOG_VAC                  157
#define IDD_DIALOG_PM                   158
#define IDB_BITMAP_FAB                  168
#define IDB_BITMAP_JUSUNG               170
#define IDC_BUTTON_LINECONTROL_RUN      1000
#define IDC_BUTTON_LINECONTROL_CLEARDATA 1001
#define IDC_BUTTON_SAVE_LOG             1001
#define IDC_BUTTON_LINECONTROL_STOP     1002
#define IDC_BUTTON_LINECONTROL_UPLOADCFG 1003
#define IDC_BUTTON_LOAD_CONFIG          1003
#define IDC_COMBO1                      1004
#define IDC_BUTTON_EXPANSION            1005
#define IDC_BUTTON_TIMELEAF             1005
#define IDC_LIST_FAB_INFO               1006
#define IDC_BUTTON_STOPTIMELEAP         1007
#define IDC_BUTTON_UNITCONTROL_RUN      1008
#define IDC_BUTTON_UNITCONTROL_CLEARDATA 1009
#define IDC_BUTTON_UNITCONTROL_STOP     1010
#define IDC_BUTTON_UNITCONTROL_UPLOADCFG 1011
#define IDC_BUTTON_TIMECONTROL_STOP     1012
#define IDC_BUTTON_TIMECONTROL_START    1013
#define IDC_BUTTON_SHRINKING            1014
#define IDC_BUTTON_SAVE                 1015
#define IDC_BUTTON_SAVE_INFO            1015
#define IDC_BUTTON_SAVE_CONFIG          1015
#define IDC_STATIC_FAB_CAPA             1016
#define IDC_STATIC_FAB_THROUGHPUT       1017
#define IDC_STATIC_THROUGHPUT           1017
#define IDC_STATIC_FAB_CELLYIELD        1018
#define IDC_STATIC_FAB_CELLEFFICIENCY   1019
#define IDC_STATIC_FAB_CELLDIMENSION    1020
#define IDC_STATIC_UNIT_OBJECTID        1021
#define IDC_STATIC_UNIT_OBJECTNAME      1022
#define IDC_STATIC_UNIT_OBJECTTHRUPUT   1023
#define IDC_STATIC_UNIT_INPUTCOUNT      1024
#define IDC_STATIC_INPUTCOUNT           1024
#define IDC_STATIC_UNIT_INPUTINTERVAL   1025
#define IDC_STATIC_UNIT_OBJECTTHRUPUT2  1025
#define IDC_STATIC_UNIT_INPUTWAIT       1026
#define IDC_STATIC_UNIT_INPUTCOUNT2     1026
#define IDC_STATIC_UNIT_OUTPUTCOUNT     1027
#define IDC_STATIC_UNIT_INPUTCOUNT4     1027
#define IDC_STATIC_UNIT_OUTPUTINTERVAL  1028
#define IDC_STATIC_UNIT_INPUTCOUNT3     1028
#define IDC_STATIC_OUTPUTCOUNT3         1028
#define IDC_STATIC_UNIT_OUTPUTWAIT      1029
#define IDC_STATIC_UNIT_INPUTCOUNT5     1029
#define IDC_STATIC_UNIT_INPUTCOUNT6     1030
#define IDC_STATIC_UNIT_OBJECTTHRUPUT3  1031
#define IDC_STATIC_UNIT_INPUTCOUNT7     1032
#define IDC_STATIC_UNIT_INPUTCOUNT8     1033
#define IDC_STATIC_UNIT_INPUTCOUNT9     1034
#define IDC_STATIC_OBJECTNAME           1050
#define IDC_EDIT_OBJECTNAME             1052
#define IDC_EDIT_RUNTIME                1053
#define IDC_COMBO_SELECTMODULE          1054
#define IDC_STATIC_RUNTIME              1056
#define IDC_TAB_MODULE                  1057
#define IDC_EDIT_LPM_OBJNAME            1058
#define IDC_EDIT_LPM_WAFERMAX           1059
#define IDC_STATIC_LPM_WAFERMAX         1060
#define IDC_STATIC_LPM_OBJNAME          1061
#define IDC_SPIN_LPM_WAFERMAX           1062
#define IDC_STATIC_ATM_OBJNAME          1063
#define IDC_EDIT_ATM_OBJNAME            1064
#define IDC_STATIC_ATM_ARM              1065
#define IDC_COMBO_ATM_ARM               1069
#define IDC_STATIC_LL_OBJNAME           1070
#define IDC_EDIT_LL_OBJNAME             1071
#define IDC_STATIC_ATM_PICKTIME         1072
#define IDC_EDIT_ATM_PICKTIME           1073
#define IDC_SPIN_ATM_PICKTIME           1074
#define IDC_STATIC_ATM_PLACETIME        1075
#define IDC_EDIT_ATM_PLACETIME          1076
#define IDC_SPIN_ATM_PLACETIME          1077
#define IDC_STATIC_ATM_ROTATETIME       1078
#define IDC_EDIT_ATM_ROTATETIME         1079
#define IDC_SPIN_ATM_ROTATETIME         1080
#define IDC_STATIC_ATM_ZROTATETIME      1081
#define IDC_EDIT_ATM_ZROTATETIME        1082
#define IDC_SPIN_ATM_ZROTATETIME        1083
#define IDC_STATIC_LL_WAFERMAX          1084
#define IDC_EDIT_LL_WAFERMAX            1085
#define IDC_SPIN_LL_WAFERMAX            1086
#define IDC_STATIC_LL_PUMPTIME          1087
#define IDC_STATIC_LL_VENTTIME          1088
#define IDC_EDIT_LL_PUMPTIME            1089
#define IDC_STATIC_LL_SLOTOPEN          1090
#define IDC_EDIT_LL_SLOTOPEN            1091
#define IDC_SPIN_LL_SLOTOPEN            1092
#define IDC_STATIC_LL_DOOROPEN          1093
#define IDC_EDIT_LL_DOOROPEN            1094
#define IDC_SPIN_LL_DOOROPEN            1095
#define IDC_STATIC_LL_SLOTCLOSE         1096
#define IDC_EDIT_LL_SLOTCLOSE           1097
#define IDC_SPIN_LL_SLOTCLOSE           1098
#define IDC_STATIC_LL_DOORCLOSE         1099
#define IDC_EDIT_LL_DOORCLOSE           1100
#define IDC_SPIN_ATM_ZROTATETIME3       1101
#define IDC_SPIN_LL_DOORCLOSE           1101
#define IDC_SPIN_LL_PUMPTIME            1102
#define IDC_EDIT_LL_VENTTIME            1103
#define IDC_SPIN_LL_VENTTIME            1104
#define IDC_STATIC_LL_PUMPSTABLE        1105
#define IDC_EDIT_LL_PUMPSTABLE          1106
#define IDC_SPIN_LL_PUMPSTABLE          1107
#define IDC_STATIC_LL_VENTSTABLE        1108
#define IDC_EDIT_LL_VENTSTABLE          1109
#define IDC_SPIN_LL_VENTSTABLE          1110
#define IDC_STATIC_VAC_OBJNAME          1111
#define IDC_EDIT_VAC_OBJNAME            1112
#define IDC_STATIC_VAC_ARM              1113
#define IDC_COMBO_VAC_ARM               1114
#define IDC_STATIC_VAC_PICKTIME         1115
#define IDC_EDIT_VAC_PICKTIME           1116
#define IDC_SPIN_VAC_PICKTIME           1117
#define IDC_STATIC_VAC_PLACETIME        1118
#define IDC_EDIT_VAC_PLACETIME          1119
#define IDC_SPIN_VAC_PLACETIME          1120
#define IDC_STATIC_VAC_ROTATETIME       1121
#define IDC_EDIT_VAC_ROTATETIME         1122
#define IDC_SPIN_VAC_ROTATETIME         1123
#define IDC_STATIC_PM_OBJNAME           1124
#define IDC_EDIT_PM_OBJNAME             1125
#define IDC_STATIC_PM_WAFERMAX          1126
#define IDC_EDIT_PM_WAFERMAX            1127
#define IDC_SPIN_PM_WAFERMAX            1128
#define IDC_STATIC_PM_PROCESSTIME       1129
#define IDC_EDIT_PM_PROCESSTIME         1130
#define IDC_SPIN_PM_PROCESSTIME         1131
#define IDC_STATIC_PM_CELANTIME         1132
#define IDC_EDIT_PM_CELANTIME           1133
#define IDC_SPIN_PM_CELANTIME           1134
#define IDC_STATIC_PM_CELANCOUNT        1135
#define IDC_EDIT_PM_CELANCOUNT          1136
#define IDC_SPIN_PM_CELANCOUNT          1137
#define IDC_STATIC_PM_SLOTOPEN          1138
#define IDC_EDIT_PM_SLOTOPEN            1139
#define IDC_SPIN_PM_SLOTOPEN            1140
#define IDC_STATIC_PM_SLOTCLOSE         1141
#define IDC_EDIT_PM_SLOTCLOSE           1142
#define IDC_SPIN_PM_SLOTCLOSE           1143
#define IDC_TAB_UPDATEMODULE            1145
#define IDC_PICTURE_LOGO                1146
#define IDC_STATIC_OUTPUT               1147
#define IDC_PICTURE_FAB                 1148
#define IDC_STATIC_OUTPUT2              1149
#define IDC_STATIC_FABTIME              1150
#define IDC_STATIC_GROUPTIME            1151
#define IDC_STATIC_OUTPUT3              1152
#define IDC_PIC_JUSUNG                  1156
#define IDC_PIC_FAB                     1157
#define ID_SUBMENU_CHANGEMODULEPROTERTY 32775
#define ID_SUBMENU_DELETEMODULE         32776
#define IDR_MENU_MODULE                 32777
#define ID_MENU_CHANGEMODULE            32778
#define ID_MENU_DELETEMODULE            32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1158
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
